# Exercise 4
<!-- Operationalize and find meet patterns  -->
<!-- Visualize spatial distribution of meet -->
<!-- Define functions -->


## Learning Outcomes


## Prerequisites


## Preperation

## Tasks

### Task 1

Find spatial overlap

```{r}
## Task 1 ####################


mcp <- wildschwein_BE_sf %>%
  group_by(TierID) %>%
  summarise() %>%
  st_convex_hull()


overlap_spatial_mat <- overlap_spatial(mcp,"TierID")

```

### Task 2

Find temporal overlap

```{r}
## Task 2 ####################
library(lubridate)

wildschwein_intervals <- wildschwein_BE_sf %>%
  group_by(TierID) %>%
  summarise(
    min = min(DatetimeUTC,na.rm = T),
    max = max(DatetimeUTC,na.rm = T)
  ) %>%
  ungroup() %>%
  mutate(
    interval = interval(min,max)
  )

overlap_temporal_mat <- overlap_temporal(wildschwein_intervals,"interval","TierID")


```

### Task 3

Combine spatial and temporal overlap and generate datframe with "pairs"
```{r}

## Task 3 ####################

overlap_spat_temp <- overlap_temporal_mat & overlap_spatial_mat

overlap_spat_temp <- overlap_spat_temp %>%
  as.data.frame() %>%
  rownames_to_column("id1") %>%
  gather(id2,bool,-id1) %>%
  filter(bool == TRUE) %>%
  dplyr::select(-bool)
```


### Task 4

Temporally join data and visualize.

<!-- Todo: remove errors -->
```{r}
## Task 4 ####################


# temporal_join(wildschwein_BE_sf,TierID,overlap_spat_temp$id1[1],overlap_spat_temp$id2[1],DatetimeUTC,mult = "first",0)
# 
# 
# ggplot(temporal_join) +
#   geom_point(aes(E2,N2), colour = "blue") +
#   geom_point(aes(E1,N1), colour = "red")
# 
# 
# leaflet(temporal_join) %>%
#   addCircles(lng = ~Long1,lat = ~Lat1) %>%
#   addTiles()

```



### Task 5
<!-- Imported via copy and paste from E03 -->

Use the package `recurse` (function `getRecursions`) to determine sites which are often visited.
<!-- Todo: either extend this task or use this as a possible challenge for the individual topics and replace this with similarity measures  -->


```{r,, echo = F, include = T}

## Task 5 #######################

library(recurse)
library(ggforce)

recurs <- wildschwein_BE_sf %>%
  filter(TierID == "001A") %>%
  dplyr::select(E,N,DatetimeUTC,TierID) %>%
  st_set_geometry(NULL) %>%
  as.data.frame() %>%
  getRecursions(100)

recurStats <- recurs$revisitStats

recurStats <- recurStats %>%
  group_by(coordIdx) %>%
  summarise(
    number_of_visits = max(visitIdx),
    x = unique(x),
    y = unique(y),
    total_time = sum(timeInside),
    max_time = max(timeInside),
    mean_time = mean(timeInside)
  )

data1 = filter(recurStats, number_of_visits > 30)
wildschwein_BE_sf %>%
  ungroup() %>%
  filter(TierID == "001A") %>%
  ggplot(aes(E,N)) +
  geom_point(alpha = 0.4, colour = "grey") +
  geom_circle(data = data1, alpha = 0.5, aes(x0 = x,y0 = y,fill = mean_time,r = 100),inherit.aes = F) +
  coord_fixed(1)

```

## Solutions (RCode)

```{r code=readLines('14_Week4/RFiles/W04_01_Exercise.R'), results='asis', echo = T, include=T, eval=F}
```
