---
title: "GEO880: Patterns and Trends in Environmental Data"
author: "Patrick Laube and Nils Ratnaweera"
site: bookdown::bookdown_site
documentclass: book
bibliography: ["00_Admin/bibliography.bib"]
output:
  bookdown::gitbook:
    number_sections: false
    config:
      toc:
        collapse: section
      download: ["pdf"]
  bookdown::pdf_book:
    number_sections: true
---
```{r include=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_chunk$set(include = F)
knitr::opts_chunk$set(eval = T)

knitr::opts_chunk$set(purl = T)

knitr::opts_chunk$set(collapse = T)
knitr::opts_chunk$set(warning = F)
knitr::opts_chunk$set(message = F)


# include = FALSE prevents code and results from appearing in the finished file. R Markdown still runs the code in the chunk, and the results can be used by other chunks.

# echo = FALSE prevents code, but not the results from appearing in the finished file. This is a useful way to embed figures.

# message = FALSE prevents messages that are generated by code from appearing in the finished file.

# warning = FALSE prevents warnings that are generated by code from appearing in the finished.

# fig.cap = "..." adds a caption to graphical results.

# See the R Markdown Reference Guide for a complete list of knitr chunk options.
# https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf
```

# Introduction Chapter {-}

For our practical `R` course building-up skills for analyzing movement data in the software environment `R`, you'll be using data from the ZHAW project ["Prävention von Wildschweinschäden in der Landwirtschaft"](https://www.zhaw.ch/de/lsfm/institute-zentren/iunr/integrative-oekologie/wildtiermanagement/referenzprojekte/).

The project investigates the spatiotemporal movement patterns of wild boar (*Sus scrofa*) in agricultural landscapes. 
For more information you can ask [Beni Sigrist](https://www.zhaw.ch/de/ueber-uns/person/sigb/), one of the course participants involved in this project. We will study the trajectories of these wild boar, practicing the most basic analysis tasks of Computational Movement Analysis (CMA). 

**Please note** we are given application data from an ongoing research project. Capturing wild living animals and then equipping them with GPS collars is a very labor and cost intensive form of research. Consequently, data resulting such campaigns is a very valuable asset that must be protected. So, please do not pass on this data, for any use beyond this module contact Patrick Laube or the data owner Stefan Suter (suts@zhaw.ch).



<!-- todo -->
<!-- Introduce some basic concepts -->

<!-- - RStudio -->
<!-- - Tidyverse -->
<!-- - datacamp -->
<!-- - Rstudio Server / Rstudio Connect -->
<!-- - Links to GIS Ressources -->
<!--   - Animove Cheet sheets -->
<!--   - GIS in R -->
<!-- - GIT / CMAtools -->

