### Task1
```{r, echo = T,include = T,eval = F}

# Loading enironment / libraries ####
library(tidyverse)



# Data import ####

# Data clensing ####

# Data analysis and visualization ####

```
### Task 2
```{r, echo = T,include = T,eval = F}

# Data import ####
wildschwein_BE <- read_delim("../CMA_FS2018_Filestorage/wildschwein_BE.csv",",")


# Check Timezone
attr(wildschwein_BE$DatetimeUTC,"tzone") # or
wildschwein_BE$DatetimeUTC[1]
```
### Task 3
```{r, echo = T,include = T,eval = F}
ggplot(wildschwein_BE, aes(Long,Lat, colour = TierID)) +
  geom_point() +
  coord_map() +
  theme(legend.position = "none")
```
### Input
```{r, echo = T,include = T,eval = F}

library(sf)

wildschwein_BE_sf <- st_as_sf(wildschwein_BE, coords = c("Long", "Lat"), crs = 4326)

wildschwein_BE

wildschwein_BE_sf
wildschwein_BE = st_as_sf(wildschwein_BE, coords = c("Long", "Lat"), crs = 4326,remove = FALSE)

wildschwein_BE # note how the Lat/Long information is stored twice

rm(wildschwein_BE_sf) # we can remove this sf object, since it just eats up our memory

```
### Task 4
```{r, echo = T,include = T,eval = F}

wildschwein_BE <- st_transform(wildschwein_BE, 2056)


wildschwein_BE
```
### Input
```{r, echo = T,include = T,eval = F}
wildschwein_BE <- group_by(wildschwein_BE,TierID)
wildschwein_BE
mcp <- st_convex_hull(summarise(wildschwein_BE))

```
### Task 5
```{r, echo = T,include = T,eval = F}
plot(mcp)
ggplot(mcp,aes(fill = TierID)) +
  geom_sf(alpha = 0.4)
ggplot(mcp,aes(fill = TierID)) +
  geom_sf(alpha = 0.4) +
  coord_sf(datum = 2056)
```
### Task 6
```{r, echo = T,include = T,eval = F}

library(raster)
library(ggspatial)

pk100_BE <- brick("../CMA_FS2018_Filestorage/pk100_BE_2056.tif")

ggplot(mcp,aes(fill = TierID)) +
  geom_spraster_rgb(pk100_BE, interpolate = TRUE) +
  geom_sf(alpha = 0.4) +
  coord_sf(datum = 2056) +
  theme(
    legend.position = "none",
    panel.grid.major = element_line(colour = "transparent"),
    panel.background = element_rect(fill = "transparent"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
    )

```
