# on:
#   push:
#     branches:
#       - main
#       - master
# 
# name: Push to computationalmovementanalysis.github.io
# 
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env:
#       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v2
# 
#       - name: Pushes to another repository  
#         uses: cpina/github-action-push-to-another-repository@main
#         env:
#           API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#         with:
#           source-directory: 'docs'
#           destination-github-username: 'ratnanil'
#           destination-repository-name: 'computationalmovementanalysis.github.io'
#           destination-repository-username: 'ComputationalMovementAnalysis'
#           user-email: 'rata@zhaw.ch'
#           commit-message: 'updated html files'
